package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class CombustivelAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustivelAllPropertiesEquals(Combustivel expected, Combustivel actual) {
        assertCombustivelAutoGeneratedPropertiesEquals(expected, actual);
        assertCombustivelAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustivelAllUpdatablePropertiesEquals(Combustivel expected, Combustivel actual) {
        assertCombustivelUpdatableFieldsEquals(expected, actual);
        assertCombustivelUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustivelAutoGeneratedPropertiesEquals(Combustivel expected, Combustivel actual) {
        assertThat(expected)
            .as("Verify Combustivel auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustivelUpdatableFieldsEquals(Combustivel expected, Combustivel actual) {
        assertThat(expected)
            .as("Verify Combustivel relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertCombustivelUpdatableRelationshipsEquals(Combustivel expected, Combustivel actual) {
        // empty method
    }
}
