package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class FornecedorAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAllPropertiesEquals(Fornecedor expected, Fornecedor actual) {
        assertFornecedorAutoGeneratedPropertiesEquals(expected, actual);
        assertFornecedorAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAllUpdatablePropertiesEquals(Fornecedor expected, Fornecedor actual) {
        assertFornecedorUpdatableFieldsEquals(expected, actual);
        assertFornecedorUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorAutoGeneratedPropertiesEquals(Fornecedor expected, Fornecedor actual) {
        assertThat(expected)
            .as("Verify Fornecedor auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorUpdatableFieldsEquals(Fornecedor expected, Fornecedor actual) {
        assertThat(expected)
            .as("Verify Fornecedor relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getCnpj()).as("check cnpj").isEqualTo(actual.getCnpj()))
            .satisfies(e -> assertThat(e.getTelefone()).as("check telefone").isEqualTo(actual.getTelefone()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()))
            .satisfies(e -> assertThat(e.getBairro()).as("check bairro").isEqualTo(actual.getBairro()))
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getUf()).as("check uf").isEqualTo(actual.getUf()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertFornecedorUpdatableRelationshipsEquals(Fornecedor expected, Fornecedor actual) {
        assertThat(expected)
            .as("Verify Fornecedor relationships")
            .satisfies(e -> assertThat(e.getInstituicao()).as("check instituicao").isEqualTo(actual.getInstituicao()));
    }
}
