package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class InstituicaoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstituicaoAllPropertiesEquals(Instituicao expected, Instituicao actual) {
        assertInstituicaoAutoGeneratedPropertiesEquals(expected, actual);
        assertInstituicaoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstituicaoAllUpdatablePropertiesEquals(Instituicao expected, Instituicao actual) {
        assertInstituicaoUpdatableFieldsEquals(expected, actual);
        assertInstituicaoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstituicaoAutoGeneratedPropertiesEquals(Instituicao expected, Instituicao actual) {
        assertThat(expected)
            .as("Verify Instituicao auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstituicaoUpdatableFieldsEquals(Instituicao expected, Instituicao actual) {
        assertThat(expected)
            .as("Verify Instituicao relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()))
            .satisfies(e -> assertThat(e.getTelefone()).as("check telefone").isEqualTo(actual.getTelefone()))
            .satisfies(e -> assertThat(e.getCnpj()).as("check cnpj").isEqualTo(actual.getCnpj()))
            .satisfies(e -> assertThat(e.getCep()).as("check cep").isEqualTo(actual.getCep()))
            .satisfies(e -> assertThat(e.getEndereco()).as("check endereco").isEqualTo(actual.getEndereco()))
            .satisfies(e -> assertThat(e.getBairro()).as("check bairro").isEqualTo(actual.getBairro()))
            .satisfies(e -> assertThat(e.getCidade()).as("check cidade").isEqualTo(actual.getCidade()))
            .satisfies(e -> assertThat(e.getNumero()).as("check numero").isEqualTo(actual.getNumero()))
            .satisfies(e -> assertThat(e.getUf()).as("check uf").isEqualTo(actual.getUf()))
            .satisfies(e -> assertThat(e.getComplemento()).as("check complemento").isEqualTo(actual.getComplemento()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertInstituicaoUpdatableRelationshipsEquals(Instituicao expected, Instituicao actual) {
        // empty method
    }
}
