package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class LocalAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllPropertiesEquals(Local expected, Local actual) {
        assertLocalAutoGeneratedPropertiesEquals(expected, actual);
        assertLocalAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAllUpdatablePropertiesEquals(Local expected, Local actual) {
        assertLocalUpdatableFieldsEquals(expected, actual);
        assertLocalUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalAutoGeneratedPropertiesEquals(Local expected, Local actual) {
        assertThat(expected)
            .as("Verify Local auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableFieldsEquals(Local expected, Local actual) {
        assertThat(expected)
            .as("Verify Local relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertLocalUpdatableRelationshipsEquals(Local expected, Local actual) {
        assertThat(expected)
            .as("Verify Local relationships")
            .satisfies(e -> assertThat(e.getInstituicao()).as("check instituicao").isEqualTo(actual.getInstituicao()));
    }
}
