package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class MarcaAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAllPropertiesEquals(Marca expected, Marca actual) {
        assertMarcaAutoGeneratedPropertiesEquals(expected, actual);
        assertMarcaAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAllUpdatablePropertiesEquals(Marca expected, Marca actual) {
        assertMarcaUpdatableFieldsEquals(expected, actual);
        assertMarcaUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaAutoGeneratedPropertiesEquals(Marca expected, Marca actual) {
        assertThat(expected)
            .as("Verify Marca auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaUpdatableFieldsEquals(Marca expected, Marca actual) {
        assertThat(expected)
            .as("Verify Marca relevant properties")
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertMarcaUpdatableRelationshipsEquals(Marca expected, Marca actual) {
        // empty method
    }
}
