package com.hubcarspot.api.domain;

import static org.assertj.core.api.Assertions.assertThat;

public class StatusDocumentoAsserts {

    /**
     * Asserts that the entity has all properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDocumentoAllPropertiesEquals(StatusDocumento expected, StatusDocumento actual) {
        assertStatusDocumentoAutoGeneratedPropertiesEquals(expected, actual);
        assertStatusDocumentoAllUpdatablePropertiesEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all updatable properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDocumentoAllUpdatablePropertiesEquals(StatusDocumento expected, StatusDocumento actual) {
        assertStatusDocumentoUpdatableFieldsEquals(expected, actual);
        assertStatusDocumentoUpdatableRelationshipsEquals(expected, actual);
    }

    /**
     * Asserts that the entity has all the auto generated properties (fields/relationships) set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDocumentoAutoGeneratedPropertiesEquals(StatusDocumento expected, StatusDocumento actual) {
        assertThat(expected)
            .as("Verify StatusDocumento auto generated properties")
            .satisfies(e -> assertThat(e.getId()).as("check id").isEqualTo(actual.getId()));
    }

    /**
     * Asserts that the entity has all the updatable fields set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDocumentoUpdatableFieldsEquals(StatusDocumento expected, StatusDocumento actual) {
        assertThat(expected)
            .as("Verify StatusDocumento relevant properties")
            .satisfies(e -> assertThat(e.getInstituicaoId()).as("check instituicaoId").isEqualTo(actual.getInstituicaoId()))
            .satisfies(e -> assertThat(e.getNome()).as("check nome").isEqualTo(actual.getNome()));
    }

    /**
     * Asserts that the entity has all the updatable relationships set.
     *
     * @param expected the expected entity
     * @param actual the actual entity
     */
    public static void assertStatusDocumentoUpdatableRelationshipsEquals(StatusDocumento expected, StatusDocumento actual) {
        assertThat(expected)
            .as("Verify StatusDocumento relationships")
            .satisfies(e -> assertThat(e.getInstituicao()).as("check instituicao").isEqualTo(actual.getInstituicao()));
    }
}
